package at.jku.se.gruppe2.domain.service.device;

import at.jku.se.gruppe2.domain.model.device.sensor.*;
import at.jku.se.gruppe2.infrastructure.config.LocalSecrets;
import at.jku.se.gruppe2.application.integration.RoboflowWorkflowService;

import java.util.*;
import java.util.concurrent.*;

/**
 * Simulates sensor readings for rooms in fixed intervals and writes values directly
 * into the corresponding {@link Sensor} objects via {@link Sensor#setValue(double)}.
 *
 * <p>Supported sensors (per room):
 * <ul>
 *   <li>{@link CO2Sensor} (ppm)</li>
 *   <li>{@link NoiseSensor} (dB)</li>
 *   <li>{@link Thermometer} (°C)</li>
 *   <li>{@link HumiditySensor} (%)</li>
 *   <li>{@link LightSensor} (lux)</li>
 *   <li>{@link CatSensor} (confidence 0..1) - uses Roboflow workflow calls</li>
 * </ul>
 *
 * <h3>Simulation model</h3>
 * <p>Each room maintains a baseline value per sensor type. On every tick, baselines drift slowly,
 * can be influenced by occasional "events" (e.g., many people -> CO₂ spikes), and then a final
 * measured value is generated by adding noise.</p>
 *
 * <h3>Concurrency</h3>
 * <ul>
 *   <li>The periodic simulation tick runs on a single scheduled executor.</li>
 *   <li>Cat detection calls are executed asynchronously on a separate executor to avoid blocking ticks.</li>
 * </ul>
 *
 * <h3>External dependency</h3>
 * <p>Cat detection uses {@link RoboflowWorkflowService} and requires an API key via {@link LocalSecrets}.
 * To reduce external calls, each room performs at most one Roboflow call every
 * {@link #CAT_CALL_INTERVAL_MS} milliseconds.</p>
 */
public class SensorSimulationService {

    /**
     * Scheduler for periodic simulation ticks.
     */
    private final ScheduledExecutorService exec = Executors.newSingleThreadScheduledExecutor();

    /**
     * Random number generator used for drift/noise/events.
     */
    private final Random rnd = new Random();

    /**
     * Executor for asynchronous Roboflow calls to avoid blocking the tick loop.
     */
    private final java.util.concurrent.ExecutorService roboflowExec =
            java.util.concurrent.Executors.newSingleThreadExecutor();

    /**
     * Test images used for the cat detection workflow (mixed: cat/non-cat).
     */
    private static final List<String> TEST_IMAGES = List.of(
            //waschbär
            "https://i.imgur.com/t6gGR4V.jpg",

            // cats
            "https://i.imgur.com/BxKNfWu.jpeg",
            "https://i.imgur.com/4XynTW7.jpeg",

            // no cats
            "https://i.imgur.com/IuqtS85.jpeg",
            "https://i.imgur.com/tgfa41l.jpeg",
            "https://i.imgur.com/dm871pH.jpeg"

    );

    /**
     * Per room: next image index for {@link #TEST_IMAGES}.
     */
    private final Map<Integer, Integer> catImageIndexByRoom = new ConcurrentHashMap<>();

    /**
     * Per room: last Roboflow call timestamp in ms.
     */
    private final Map<Integer, Long> catLastCallMs = new ConcurrentHashMap<>();

    /**
     * Interval between Roboflow calls per room.
     */
    private static final long CAT_CALL_INTERVAL_MS = 10_000;

    // Per-room sensor instances
    private final Map<Integer, CO2Sensor> co2ByRoom = new ConcurrentHashMap<>();
    private final Map<Integer, NoiseSensor> noiseByRoom = new ConcurrentHashMap<>();
    private final Map<Integer, Thermometer> thermoByRoom = new ConcurrentHashMap<>();
    private final Map<Integer, HumiditySensor> humidityByRoom = new ConcurrentHashMap<>();
    private final Map<Integer, LightSensor> lightByRoom = new ConcurrentHashMap<>();

    // Per-room baselines
    private final Map<Integer, Double> co2Baseline = new ConcurrentHashMap<>();
    private final Map<Integer, Double> noiseBaseline = new ConcurrentHashMap<>();
    private final Map<Integer, CatSensor> catByRoom = new ConcurrentHashMap<>();
    private final Map<Integer, Double> thermoBaseline = new ConcurrentHashMap<>();
    private final Map<Integer, Double> humidityBaseline = new ConcurrentHashMap<>();
    private final Map<Integer, Double> lightBaseline = new ConcurrentHashMap<>();

    /**
     * Indicates whether the periodic simulation tick is currently active.
     */
    private volatile boolean running = false;

    /**
     * Roboflow workflow client used for cat detection.
     */
    private final RoboflowWorkflowService roboflow =
            new RoboflowWorkflowService(LocalSecrets.ROBOFLOW_API_KEY, 0.75);


    /**
     * Registers a sensor for a specific room so it will be updated during simulation ticks.
     *
     * <p>On first registration for a sensor type, a default baseline is created for the room.</p>
     *
     * @param roomId room identifier used as key for sensor/baseline maps
     * @param sensor sensor instance to simulate (must be one of the supported sensor types)
     */
    public void registerSensor(int roomId, Sensor sensor) {

        if (sensor instanceof CO2Sensor co2) {
            co2ByRoom.put(roomId, co2);
            co2Baseline.putIfAbsent(roomId, 650.0);
        }

        if (sensor instanceof NoiseSensor noise) {
            noiseByRoom.put(roomId, noise);
            noiseBaseline.putIfAbsent(roomId, 35.0);
        }
        if (sensor instanceof CatSensor cat) {
            catByRoom.put(roomId, cat);
            catImageIndexByRoom.putIfAbsent(roomId, 0);
        }
        if (sensor instanceof Thermometer t) {
            thermoByRoom.put(roomId, t);
            thermoBaseline.putIfAbsent(roomId, 21.0); // z.B. Start bei 21°C
        }
        if (sensor instanceof HumiditySensor h) {
            humidityByRoom.put(roomId, h);
            humidityBaseline.putIfAbsent(roomId, 45.0); // Start: 45%
        }
        if (sensor instanceof LightSensor l) {
            lightByRoom.put(roomId, l);
            lightBaseline.putIfAbsent(roomId, 300.0); // Start z.B. 300 lux
        }
        //TODO: weitere Sensoren hinzufügen
    }

    /**
     * Starts periodic simulation ticks.
     *
     * @param everySeconds tick interval in seconds (must be &gt; 0)
     * @throws IllegalArgumentException if {@code everySeconds &lt;= 0}
     */
    public void start(int everySeconds) {
        if (everySeconds <= 0) throw new IllegalArgumentException("everySeconds must be > 0");
        if (running) return;
        running = true;
        exec.scheduleAtFixedRate(this::tick, 0, everySeconds, TimeUnit.SECONDS);
    }

    /**
     * Stops the simulation and shuts down internal executors immediately.
     *
     * <p>After calling this method, the service instance cannot be restarted,
     * because the executors are shut down.</p>
     */
    public void stop() {
        running = false;
        exec.shutdownNow();
        roboflowExec.shutdownNow();
    }

    /**
     * Removes all registered sensors and baseline state for the given room.
     *
     * @param roomId room identifier
     */
    public void clearRoom(int roomId) {
        co2ByRoom.remove(roomId);
        noiseByRoom.remove(roomId);
        co2Baseline.remove(roomId);
        noiseBaseline.remove(roomId);
        catByRoom.remove(roomId);
        catImageIndexByRoom.remove(roomId);
        thermoByRoom.remove(roomId);
        thermoBaseline.remove(roomId);
        humidityByRoom.remove(roomId);
        humidityBaseline.remove(roomId);
        lightByRoom.remove(roomId);
        lightBaseline.remove(roomId);
    }

    /**
     * Single simulation tick. Updates all registered sensor types room-by-room.
     *
     * <p>Cat detection is rate-limited and executed asynchronously.</p>
     */
    private void tick() {
        if (!running) return;

        // CO2-Sensoren simulieren
        for (Integer roomId : co2ByRoom.keySet()) {
            simulateCo2(roomId);
        }

        // Geräuschsensoren simulieren
        for (Integer roomId : noiseByRoom.keySet()) {
            simulateNoise(roomId);
        }
        for (Integer roomId : thermoByRoom.keySet()) {
            simulateThermometer(roomId);
        }
        for (Integer roomId : humidityByRoom.keySet()) {
            simulateHumidity(roomId);
        }
        for (Integer roomId : lightByRoom.keySet()) {
            simulateLight(roomId);
        }
        //TODO: weitere Sensoren hinzufügen
        for (Integer roomId : catByRoom.keySet()) {
            simulateCat(roomId);
        }
    }

    /**
     * Simulates light in lux. Baseline drifts with occasional spikes/drops.
     *
     * @param roomId room identifier
     */
    private void simulateLight(Integer roomId) {
        LightSensor sensor = lightByRoom.get(roomId);
        if (sensor == null) return;

        double base = lightBaseline.getOrDefault(roomId, 300.0);

        // leichte Drift
        base += rnd.nextGaussian() * 30.0;

        // seltenes Event: Sonne kommt raus / Licht geht an
        if (rnd.nextDouble() < 0.08) {
            base += 200 + rnd.nextDouble() * 1200; // +200..+1400
        }

        // seltenes Event: Wolke / Licht aus
        if (rnd.nextDouble() < 0.06) {
            base -= 150 + rnd.nextDouble() * 800; // -150..-950
        }

        // clamp baseline (0..5000 lux)
        base = clamp(base, 0, 5000);
        lightBaseline.put(roomId, base);

        // final messwert
        double value = clamp(base + rnd.nextGaussian() * 20.0, 0, 10000);

        sensor.setValue(value);
    }

    /**
     * Simulates humidity in percent with drift and occasional "events".
     *
     * @param roomId room identifier
     */
    private void simulateHumidity(Integer roomId) {
        HumiditySensor sensor = humidityByRoom.get(roomId);
        if (sensor == null) return;

        double base = humidityBaseline.getOrDefault(roomId, 45.0);

        // langsamer Drift
        double target = 48.0;
        base += (target - base) * 0.05;

        // leichtes Rauschen
        base += rnd.nextGaussian() * 0.6;

        // seltenes Event: Feuchtigkeit steigt (Duschen/Kochen)
        if (rnd.nextDouble() < 0.06) { // 6% pro Tick
            base += 4.0 + rnd.nextDouble() * 12.0; // +4..+16%
        }

        // seltenes Event: Lüften/trockene Luft
        if (rnd.nextDouble() < 0.04) { // 4% pro Tick
            base -= 3.0 + rnd.nextDouble() * 10.0; // -3..-13%
        }

        // baseline clamp
        base = clamp(base, 20, 80);
        humidityBaseline.put(roomId, base);

        // finaler Messwert
        double value = clamp(base + rnd.nextGaussian() * 0.3, 10, 95);

        sensor.setValue(value);
    }

    /**
     * Simulates cat detection by calling Roboflow on rotating test images.
     *
     * <p>Rate-limited per room to avoid excessive external API calls.</p>
     *
     * @param roomId room identifier
     */
    private void simulateCat(int roomId) {
        CatSensor sensor = catByRoom.get(roomId);
        if (sensor == null) return;

        long now = System.currentTimeMillis();
        long last = catLastCallMs.getOrDefault(roomId, 0L);
        if (now - last < CAT_CALL_INTERVAL_MS) return;
        catLastCallMs.put(roomId, now);

        int idx = catImageIndexByRoom.getOrDefault(roomId, 0);
        String imageUrl = TEST_IMAGES.get(idx);

        // Index weiterdrehen
        idx = (idx + 1) % TEST_IMAGES.size();
        catImageIndexByRoom.put(roomId, idx);

        roboflowExec.submit(() -> {
            try {
                RoboflowWorkflowService.DetectionResult result =
                        roboflow.detectCatFromImageUrlAsBase64(imageUrl);

                sensor.updateDetection(result.confidence(), imageUrl);
            } catch (Exception e) {
                sensor.updateDetection(0.0, imageUrl);
                System.err.println("Roboflow failed for: " +imageUrl + " -> " + e.getMessage());
            }
        });
    }

    /**
     * Simulates CO₂ concentration in ppm with drift and occasional spikes.
     *
     * @param roomId room identifier
     */
    private void simulateCo2(int roomId) {
        CO2Sensor sensor = co2ByRoom.get(roomId);
        if (sensor == null) return;

        double base = co2Baseline.getOrDefault(roomId, 650.0);

        // kleine Drift
        base += rnd.nextGaussian() * 20.0;

        // seltenes "Event": viele Leute im Raum / schlechte Luft
        if (rnd.nextDouble() < 0.08) { // 8% pro Tick
            base += 200 + rnd.nextDouble() * 600; // +200..+800
        }

        // clamp realistisch: 400..2500 ppm
        base = clamp(base, 400, 2500);

        co2Baseline.put(roomId, base);

        // finaler Messwert mit leichtem Rauschen
        double value = clamp(base + rnd.nextGaussian() * 15.0, 400, 3000);

        sensor.setValue(value);
    }

    /**
     * Simulates noise level in dB with drift and occasional noise events.
     *
     * @param roomId room identifier
     */
    private void simulateNoise(int roomId) {
        NoiseSensor sensor = noiseByRoom.get(roomId);
        if (sensor == null) return;

        double base = noiseBaseline.getOrDefault(roomId, 35.0);

        // kleine Drift
        base += rnd.nextGaussian() * 2.0;

        // seltenes "Lärm-Event": Tür knallt / laute Musik / Streit
        if (rnd.nextDouble() < 0.10) { // 10% pro Tick
            base += 20 + rnd.nextDouble() * 50; // +20..+70 dB extra
        }

        // clamp baseline: 25..80
        base = clamp(base, 25, 80);

        noiseBaseline.put(roomId, base);

        // Messwert: baseline + event noise
        double value = clamp(base + Math.abs(rnd.nextGaussian() * 3.0), 20, 120);

        sensor.setValue(value);
    }

    /**
     * Simulates room temperature in Celsius with slight drift and occasional events.
     *
     * @param roomId room identifier
     */
    private void simulateThermometer(int roomId) {
        Thermometer sensor = thermoByRoom.get(roomId);
        if (sensor == null) return;

        double base = thermoBaseline.getOrDefault(roomId, 21.0);

        // kleine Drift
        base += rnd.nextGaussian() * 0.15; // ca ±0.15°C

        // seltenes Event (Fenster offen / Sonne / Heizung an)
        if (rnd.nextDouble() < 0.05) {
            base += (rnd.nextBoolean() ? 1 : -1) * (0.5 + rnd.nextDouble() * 1.5); // ±0.5..2.0°C
        }

        base = clamp(base, 15, 30);
        thermoBaseline.put(roomId, base);

        // finaler Messwert mit kleinem Rauschen
        double value = clamp(base + rnd.nextGaussian() * 0.05, 10, 35);
        sensor.setValue(value);
    }

    /**
     * Clamps a double value to an inclusive range.
     *
     * @param v   input value
     * @param min minimum allowed value
     * @param max maximum allowed value
     * @return clamped value in range {@code [min, max]}
     */
    private double clamp(double v, double min, double max) {
        return Math.max(min, Math.min(max, v));
    }
}